defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Safety
safe: true
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true

# Other
timezone: "Europe/Berlin"
