defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Safety
safe: true
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true

# Other
timezone: "Europe/Berlin"

# SEO
description: "Åndsliv har til formål at bidrage kritisk til den aktuelle samfundsdebat, ved at tilbyde alternative forståelsesrammer til den dominerende diskurs' bevægelse væk fra de menneskelige værdier."
