defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Where to find things
# source: ./src
# destination: ./_site
# collections_dir: ./src/
# layouts_dir: ./src/_layouts
# data_dir: ./src/_data
# includes_dir: ./src/_includes
baseurl: "https://aandsliv.dk"
url: "https://aandsliv.dk"
# exclude: [ "_config.yml", ".editorconfig", ".gitattrbutes", ".gitignore", "Gemfile", "Gemfile.lock", "README.md", ".github/" ]
# include: [ "./src" ]

# Safety
safe: true
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
  # strict_variables: true # disabled because of error in feed plugin

# Other
timezone: "Europe/Berlin"
